# Generated by Django 2.2.1 on 2019-05-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='titulo',
        ),
    ]
