# Generated by Django 2.2.1 on 2019-05-28 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasklist', '0002_auto_20190527_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='data_conclusao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='data_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='descricao',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
